import { useEffect, useState } from "react";
import { useLocation } from "../context/LocationContext";

const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], SLOTS=["Breakfast","Lunch","Dinner"];
export function IngredientDetailModal({ingredientId,headers,apiUrl="",formatPrice,onClose}) {
  const [data,setData]=useState(null),[selected,setSelected]=useState(null),[day,setDay]=useState("Mon"),[slot,setSlot]=useState("Lunch");
  const location=useLocation();
  useEffect(()=>{const controller=new AbortController();setData(null);fetch(`${apiUrl}/api/ingredients/${ingredientId}/stores`,{headers,signal:controller.signal}).then(r=>r.json()).then(setData).catch(error=>{if(error.name!=="AbortError")setData(null)});return()=>controller.abort()},[ingredientId,location.latitude,location.longitude]);
  if(!data)return <div className="fixed inset-0 z-40 grid place-items-center bg-emerald-700/40"><div className="rounded-2xl bg-white p-6">Loading ingredient…</div></div>;
  const n=data.ingredient, addSuggested=()=>{if(data.suggested_recipe_id){dispatchEvent(new CustomEvent("planner:add",{detail:{day,slot,recipeId:data.suggested_recipe_id}}));onClose()}};
  return <div className="fixed inset-0 z-40 overflow-auto bg-emerald-700/45 p-4 backdrop-blur-sm"><section className="mx-auto my-8 max-w-2xl rounded-3xl border border-slate-800/10 bg-white p-6 shadow-2xl"><header className="flex justify-between"><div><p className="text-sm font-bold text-emerald-600">INGREDIENT DETAILS</p><h2 className="text-3xl font-bold capitalize text-emerald-700">{n.name}</h2></div><button onClick={onClose} className="text-2xl">×</button></header><div className="mt-5 flex flex-wrap gap-2">{[["Calories",n.calories_per_100g],["Protein",`${n.protein_g_per_100g}g`],["Carbs",`${n.carbs_g_per_100g}g`],["Fats",`${n.fat_g_per_100g}g`],["Fiber",`${n.fiber_g_per_100g}g`]].map(x=><span key={x[0]} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-emerald-700">{x[0]} {x[1]}</span>)}</div><h3 className="mt-7 font-bold">Nearby stores</h3><div className="mt-3 max-h-80 space-y-3 overflow-auto">{data.stores.map(store=><article key={store.store_id} className={`rounded-2xl border p-4 ${selected===store.store_id?"border-emerald-700 bg-slate-100/40":"border-emerald-700/10"}`}><div className="flex justify-between gap-4"><div><b>{store.branch_name || store.store_name}</b><p className="text-xs text-zinc-900/55">{store.street_address || store.address}</p><p className="text-sm text-zinc-900/55">{store.distance_km} km · {store.in_stock?"In stock":"Reported out of stock"}</p><b className="mt-1 block text-emerald-700">{formatPrice(store.price_usd)} / {store.unit}</b></div><div className="flex flex-col gap-2"><button onClick={()=>setSelected(store.store_id)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold">{selected===store.store_id?"Selected ✓":"Select Store"}</button><a href={store.navigation_url} target="_blank" rel="noopener noreferrer" className="rounded-lg bg-emerald-700 px-3 py-2 text-center text-xs font-bold text-white">Navigate ↗</a></div></div></article>)}</div>{data.suggested_recipe_id&&<div className="mt-5 rounded-2xl bg-slate-100 p-4"><p className="text-sm font-bold">Add a matching dish: {data.suggested_recipe_title}</p><div className="mt-3 flex flex-wrap gap-2"><select value={day} onChange={e=>setDay(e.target.value)} className="rounded-lg border p-2">{DAYS.map(x=><option key={x}>{x}</option>)}</select><select value={slot} onChange={e=>setSlot(e.target.value)} className="rounded-lg border p-2">{SLOTS.map(x=><option key={x}>{x}</option>)}</select><button onClick={addSuggested} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white">Add to Weekly Planner</button></div></div>}</section></div>;
}
