import { useEffect, useState } from "react";

const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], SLOTS=["Breakfast","Lunch","Dinner"];
function CoverageBadge({ item }) {
  if (item.coverage_status === "FULLY_OWNED") return <span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">✓ Already owned</span>;
  if (item.coverage_status === "PARTIALLY_OWNED") return <span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-800">Need {item.missing_quantity}{item.unit}</span>;
  return <span className="rounded-full bg-slate-200 px-2 py-1 text-[10px] font-bold text-zinc-700">Missing</span>;
}

export function RecipeDetailModal({ recipe, headers, apiUrl="", formatPrice, onClose }) {
  const [tab,setTab]=useState("details"), [view,setView]=useState("itemized"), [source,setSource]=useState(null), [day,setDay]=useState("Mon"), [slot,setSlot]=useState(recipe.meal_type||"Lunch");
  useEffect(() => { fetch(`${apiUrl}/api/recipes/${recipe.id}/sourcing`,{headers}).then(response => response.json()).then(setSource); },[recipe.id]);
  function addToPlanner(){ dispatchEvent(new CustomEvent("planner:add",{detail:{day,slot,recipeId:recipe.id}})); onClose(); }
  const itemized=source?.itemized_sourcing, baseline=source?.best_single_store;
  return <div className="fixed inset-0 z-40 overflow-auto bg-zinc-900/55 p-4 backdrop-blur-sm"><section className="mx-auto my-8 max-w-5xl rounded-[2rem] bg-white p-6 shadow-2xl"><header className="flex justify-between gap-4"><div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">{recipe.meal_type}</span><h2 className="mt-3 text-3xl font-bold text-zinc-900">{recipe.title}</h2></div><button onClick={onClose} className="text-2xl text-slate-500">×</button></header>
    <div className="mt-5 flex gap-2 border-b border-slate-200"><button onClick={() => setTab("details")} className={`px-4 py-3 font-bold ${tab==="details"?"border-b-2 border-emerald-700 text-emerald-700":"text-slate-500"}`}>Dish Details</button><button onClick={() => setTab("sourcing")} className={`px-4 py-3 font-bold ${tab==="sourcing"?"border-b-2 border-emerald-700 text-emerald-700":"text-slate-500"}`}>Sourcing & Stores</button></div>
    {tab === "details" ? <div className="py-6"><div className="grid gap-3 sm:grid-cols-4">{[["Calories",recipe.calories],["Protein",`${recipe.protein_g}g`],["Carbs",`${recipe.carbs_g}g`],["Fats",`${recipe.fat_g}g`]].map(([label,value]) => <div key={label} className="rounded-2xl bg-slate-100 p-4"><small className="font-bold text-emerald-700">{label}</small><b className="block text-xl text-zinc-900">{value}</b></div>)}</div><p className="mt-5 leading-7 text-slate-600">Prep time: {recipe.prep_time} minutes. Ranked using pantry coverage, nutrition fit, exclusions and the local cost of only the missing quantities.</p></div> : <div className="py-6">{!source ? <p className="text-slate-600">Comparing local packages and stock…</p> : <>
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold text-emerald-700">ITEM-LEVEL INGREDIENT TOTAL</p><b className="text-4xl text-zinc-900">{formatPrice(itemized.ingredient_total_usd)}</b><p className="mt-1 text-sm text-slate-500">{itemized.stores.length} stop{itemized.stores.length===1?"":"s"} · {itemized.travel_distance_km} km combined</p></div><div className="inline-flex rounded-full bg-slate-100 p-1 text-xs font-bold"><button onClick={() => setView("itemized")} className={view==="itemized"?"rounded-full bg-emerald-700 px-4 py-2 text-white":"px-4 py-2 text-slate-600"}>Cheapest per item</button><button onClick={() => setView("single")} disabled={!baseline} className={view==="single"?"rounded-full bg-emerald-700 px-4 py-2 text-white":"px-4 py-2 text-slate-600 disabled:opacity-40"}>One-store baseline</button></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-emerald-700 p-4 text-white"><small className="text-emerald-100">Item-by-item</small><b className="block text-xl">{formatPrice(itemized.ingredient_total_usd)}</b></div><div className="rounded-2xl bg-slate-100 p-4"><small className="text-slate-500">Single-store items</small><b className="block text-xl text-zinc-900">{baseline?formatPrice(baseline.item_total_usd):"Unavailable"}</b></div><div className="rounded-2xl bg-amber-100 p-4"><small className="text-amber-800">Ingredient savings</small><b className="block text-xl text-zinc-900">{formatPrice(itemized.savings_vs_single_store_usd)}</b></div></div>
      {view === "single" && baseline ? <article className="mt-5 rounded-2xl bg-zinc-900 p-5 text-white"><p className="text-xs font-bold text-amber-400">ONE-STORE BASELINE</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><b className="text-xl">{baseline.store_name}</b><p className="text-white/60">{baseline.distance_km} km · {formatPrice(baseline.item_total_usd)} items</p></div><a href={baseline.navigation_url} target="_blank" rel="noopener noreferrer" className="rounded-xl bg-amber-400 px-4 py-3 text-center font-bold text-zinc-900">Navigate to Store ↗</a></div></article> : <>
        <h3 className="mt-7 text-lg font-bold text-zinc-900">Each item at its cheapest store</h3><div className="mt-3 overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Ingredient</th><th className="p-3">Cheapest store</th><th className="p-3">Package</th><th className="p-3">Unit price</th><th className="p-3">Cost</th><th className="p-3">Route</th></tr></thead><tbody>{itemized.assignments.map(item => <tr key={item.ingredient_name} className="border-t border-slate-200"><td className="p-3"><b className="capitalize text-zinc-900">{item.ingredient_name}</b><small className="block text-slate-500">Need {item.quantity}{item.unit}</small></td><td className="p-3"><span className="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-700">{item.store_name}</span><small className="mt-1 block text-slate-500">{item.distance_km} km</small></td><td className="p-3">{item.packages_needed} × {item.package_size}{item.package_unit}</td><td className="p-3">{formatPrice(item.unit_price_usd)} / {item.package_unit}</td><td className="p-3 font-bold">{formatPrice(item.estimated_cost_usd)}</td><td className="p-3"><a href={item.navigation_url} target="_blank" rel="noopener noreferrer" className="rounded-lg bg-zinc-900 px-3 py-2 text-xs font-bold text-white">Navigate ↗</a></td></tr>)}</tbody></table></div>
        <h3 className="mt-7 text-lg font-bold text-zinc-900">Store-by-store schedule</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{itemized.stores.map(store => <article key={store.store_id} className="rounded-2xl bg-slate-100 p-4"><div className="flex justify-between gap-3"><div><b>{store.store_name}</b><p className="text-xs text-slate-500">{store.distance_km} km · {store.ingredients.join(", ")}</p></div><b>{formatPrice(store.subtotal_usd)}</b></div><a href={store.navigation_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-xs font-bold text-emerald-700">Open directions ↗</a></article>)}</div>
      </>}
      <h3 className="mt-7 text-lg font-bold">Pantry coverage</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{source.ingredients.map(item => <div key={item.ingredient_name} className="flex items-center justify-between gap-3 rounded-xl bg-slate-100 p-3 text-sm"><div><b className="capitalize">{item.ingredient_name}</b><p className="text-xs text-slate-500">{item.pantry_quantity}{item.unit} of {item.required_quantity}{item.unit} owned</p></div><CoverageBadge item={item}/></div>)}</div>
    </>}</div>}
    <footer className="mt-4 flex flex-col justify-between gap-3 border-t border-slate-200 pt-5 sm:flex-row"><div className="flex gap-2"><select value={day} onChange={event=>setDay(event.target.value)} className="rounded-xl border border-slate-200 p-2">{DAYS.map(value=><option key={value}>{value}</option>)}</select><select value={slot} onChange={event=>setSlot(event.target.value)} className="rounded-xl border border-slate-200 p-2">{SLOTS.map(value=><option key={value}>{value}</option>)}</select></div><button onClick={addToPlanner} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Add to Weekly Planner</button></footer>
  </section></div>;
}
