import { useEffect, useState } from "react";

export function SourcingPanel({ recipeId, plan, formatPrice, headers, apiUrl="" }) {
  const [source,setSource]=useState(null);
  useEffect(() => { if(recipeId) fetch(`${apiUrl}/api/recipes/${recipeId}/sourcing`,{headers}).then(response=>response.ok?response.json():null).then(setSource); },[recipeId]);
  const itemized=source?.itemized_sourcing;
  if(!itemized) return <section className="rounded-3xl bg-zinc-900 p-6 text-white"><p className="text-sm font-bold text-amber-400">LOCAL SOURCING</p><h2 className="mt-1 text-2xl font-bold">{formatPrice(plan?.total_cost||0)}</h2><p className="mt-3 text-white/55">Loading item-level store comparisons…</p></section>;
  return <section className="rounded-3xl bg-zinc-900 p-6 text-white"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-amber-400">ITEM-BY-ITEM SOURCING</p><h2 className="text-3xl font-bold">{formatPrice(itemized.ingredient_total_usd)}</h2><p className="text-sm text-white/55">{itemized.stores.length} stops · {itemized.travel_distance_km} km</p></div><div className="rounded-xl bg-white/10 px-4 py-3 text-sm"><span className="text-white/55">Savings vs one store</span><b className="ml-2 text-amber-300">{formatPrice(itemized.savings_vs_single_store_usd)}</b></div></header><div className="mt-5 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-white/10 text-xs uppercase text-white/50"><tr><th className="p-3">Missing item</th><th className="p-3">Cheapest store</th><th className="p-3">Distance</th><th className="p-3">Unit price</th><th className="p-3">Total</th><th className="p-3">Directions</th></tr></thead><tbody>{itemized.assignments.map(item=><tr key={item.ingredient_name} className="border-t border-white/10"><td className="p-3"><b className="capitalize">{item.ingredient_name}</b><small className="block text-white/45">{item.quantity}{item.unit}</small></td><td className="p-3"><span className="rounded-full bg-emerald-600 px-3 py-1 text-xs font-bold">{item.store_name}</span></td><td className="p-3">{item.distance_km} km</td><td className="p-3">{formatPrice(item.unit_price_usd)} / {item.package_unit}</td><td className="p-3 font-bold">{formatPrice(item.estimated_cost_usd)}</td><td className="p-3"><a href={item.navigation_url} target="_blank" rel="noopener noreferrer" className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-zinc-900">Navigate ↗</a></td></tr>)}</tbody></table></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{itemized.stores.map(store=><article key={store.store_id} className="rounded-2xl bg-white/10 p-4"><div className="flex justify-between"><b>{store.store_name}</b><b className="text-amber-300">{formatPrice(store.subtotal_usd)}</b></div><p className="mt-1 text-xs text-white/55">Buy {store.ingredients.join(", ")}</p><a href={store.navigation_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-xs font-bold text-amber-300">Open route ↗</a></article>)}</div></section>;
}
