import { useEffect, useMemo, useState } from "react";
import { Header } from "../components/Header";
import { LocationBadge } from "../components/LocationBadge";

const GOALS = [["weight_loss", "Weight Loss"], ["muscle_gain", "Muscle Gain"], ["maintenance", "Maintenance"], ["budget_first", "Budget-First"]];

export function ProfileSettings({ apiUrl, headers, onBack, onNavigate, activePath, onLogout, currencySwitcher }) {
  const [profile, setProfile] = useState(null), [options, setOptions] = useState({ recipes: [], ingredients: [] }), [query, setQuery] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch(`${apiUrl}/auth/preferences`, { headers }).then(r => r.json()), fetch(`${apiUrl}/auth/onboarding-options`).then(r => r.json())]).then(([preferences, choices]) => { setProfile(preferences); setOptions(choices); }); }, []);
  const matches = useMemo(() => options.ingredients.filter(item => item.name.toLowerCase().includes(query.toLowerCase()) && !profile?.excluded_ingredient_ids.includes(item.id)).slice(0, 8), [query, options, profile]);
  if (!profile) return <p className="p-10">Loading dietary profile…</p>;
  const set = (key, value) => setProfile(current => ({ ...current, [key]: value }));
  function toggleFavorite(id) { set("favorite_meal_ids", profile.favorite_meal_ids.includes(id) ? profile.favorite_meal_ids.filter(item => item !== id) : profile.favorite_meal_ids.length < 5 ? [...profile.favorite_meal_ids, id] : profile.favorite_meal_ids); }
  async function save() {
    setMessage("");
    if (profile.favorite_meal_ids.length < 3) return setMessage("Keep at least 3 favorite meals selected.");
    const weight_goal = profile.health_goal === "weight_loss" ? "deficit" : profile.health_goal === "muscle_gain" ? "surplus" : "maintenance";
    const response = await fetch(`${apiUrl}/auth/preferences`, { method: "PATCH", headers: { ...headers, "Content-Type": "application/json" }, body: JSON.stringify({ ...profile, weight_goal, target_calories: +profile.target_calories }) });
    setMessage(response.ok ? "Preferences saved. Recommendations have been refreshed." : "Could not save preferences.");
  }
  return <main className="min-h-screen bg-slate-100"><Header onHome={onBack} onNavigate={onNavigate} activePath={activePath} onLogout={onLogout} currencySwitcher={currencySwitcher}/><div className="mx-auto max-w-5xl px-6 py-10"><button onClick={onBack} className="text-sm font-bold text-emerald-700">← Dashboard</button><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-4xl font-bold text-zinc-900">Dietary Profile & Goals</h1><LocationBadge/></div><p className="mt-2 text-slate-800/70">These preferences directly shape recipe ranking and weekly planning.</p>
    <section className="mt-8 rounded-[2rem] border border-slate-800/10 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-bold">Primary goal</h2><div className="mt-3 grid gap-2 sm:grid-cols-4">{GOALS.map(([value,label]) => <button key={value} onClick={() => set("health_goal", value)} className={`rounded-xl border p-3 font-bold ${profile.health_goal === value ? "border-emerald-700 bg-slate-100" : "border-emerald-700/10"}`}>{label}</button>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Target daily calories<input type="number" value={profile.target_calories} onChange={e => set("target_calories", e.target.value)} className="mt-1 w-full rounded-xl border border-emerald-700/10 px-4 py-3"/></label><label className="text-sm font-bold">Macro preference<select value={profile.macro_preference} onChange={e => set("macro_preference", e.target.value)} className="mt-1 w-full rounded-xl border border-emerald-700/10 px-4 py-3"><option value="balanced">Balanced</option><option value="high_protein">High Protein</option><option value="low_carb">Low Carb</option></select></label></div></section>
    <section className="mt-5 rounded-[2rem] border border-slate-800/10 bg-white p-6 shadow-sm sm:p-8"><div className="flex justify-between"><h2 className="text-xl font-bold">Favorite dishes</h2><b className="text-emerald-600">{profile.favorite_meal_ids.length}/5</b></div><div className="mt-4 grid max-h-72 gap-2 overflow-auto sm:grid-cols-2 lg:grid-cols-3">{options.recipes.map(recipe => <button key={recipe.id} onClick={() => toggleFavorite(recipe.id)} className={`rounded-xl border p-3 text-left text-sm ${profile.favorite_meal_ids.includes(recipe.id) ? "border-emerald-700 bg-slate-100" : "border-emerald-700/10"}`}><b>{recipe.title}</b><small className="block text-emerald-600">{recipe.meal_type}</small></button>)}</div></section>
    <section className="mt-5 rounded-[2rem] border border-slate-800/10 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-bold">Excluded ingredients</h2><p className="mt-1 text-sm text-zinc-900/50">Strictly removed from search, smart recipes and automatic meal plans.</p><div className="mt-4 flex flex-wrap gap-2">{profile.excluded_ingredient_ids.map(id => { const item = options.ingredients.find(x => x.id === id); return <button key={id} onClick={() => set("excluded_ingredient_ids", profile.excluded_ingredient_ids.filter(x => x !== id))} className="rounded-full bg-slate-800 px-3 py-2 text-xs font-bold text-white">{item?.name || `Ingredient ${id}`} ×</button>; })}</div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search allergens, dislikes or restrictions…" className="mt-4 w-full rounded-xl border border-emerald-700/10 px-4 py-3"/>{query && <div className="mt-2 grid gap-1 rounded-xl border border-emerald-700/10 p-2 sm:grid-cols-2">{matches.map(item => <button key={item.id} onClick={() => { set("excluded_ingredient_ids", [...profile.excluded_ingredient_ids, item.id]); setQuery(""); }} className="rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100">+ {item.name}</button>)}</div>}</section>
    {message && <p className="mt-5 rounded-xl bg-slate-100 p-3 font-semibold text-emerald-700">{message}</p>}<div className="mt-6 flex justify-end"><button onClick={save} className="rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Save dietary profile</button></div>
  </div></main>;
}
