import { useState } from "react";

const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], SLOTS = ["Breakfast", "Lunch", "Dinner"];
export function WeeklyPlanner({ recipes, formatPrice, headers, apiUrl = "" }) {
  const [selected, setSelected] = useState({}), [budget, setBudget] = useState(50), [result, setResult] = useState(null);
  const assignments = Object.entries(selected).map(([key, recipe_id]) => { const [day, slot] = key.split("-"); return { day, slot, recipe_id }; });
  async function consolidate() { const r = await fetch(`${apiUrl}/api/planner/consolidate`, { method:"POST", headers:{...headers,"Content-Type":"application/json"}, body:JSON.stringify({ assignments, weekly_budget:budget }) }); if(r.ok)setResult(await r.json()); }
  return <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-2xl font-bold text-forest">Weekly meal planner</h2><label className="text-sm font-bold">Budget <input className="ml-2 w-20 rounded border p-1" type="number" value={budget} onChange={e=>setBudget(+e.target.value)}/></label></div><div className="mt-5 overflow-x-auto"><div className="grid min-w-[700px] grid-cols-8 gap-2 text-sm"><b>Slot</b>{DAYS.map(day=><b key={day}>{day}</b>)}{SLOTS.map(slot=><><b key={slot}>{slot}</b>{DAYS.map(day=><select key={`${day}-${slot}`} className="rounded border border-forest/15 p-2" value={selected[`${day}-${slot}`]||""} onChange={e=>setSelected({...selected,[`${day}-${slot}`]:+e.target.value})}><option value="">—</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select>)}</>)}</div></div><button onClick={consolidate} className="mt-5 rounded-xl bg-forest px-4 py-3 font-bold text-white">Generate Weekly Shopping List</button>{result&&<div className="mt-4 rounded-xl bg-mint p-4"><b>{formatPrice(result.total_cost)} / {formatPrice(result.weekly_budget)} Budget</b><div className="mt-2 h-2 rounded bg-white"><div className="h-2 rounded bg-forest" style={{width:`${Math.min(100,result.total_cost/result.weekly_budget*100)}%`}}/></div>{result.exceeds_budget&&<p className="mt-2 text-sm text-red-700">Over budget: {result.swap_suggestions.join(" ")}</p>}</div>}</section>;
}
