import { useState } from "react";
import { BrandMark } from "../components/Header";

const CHAINS = ["Yerevan City", "SAS", "Carrefour", "Parma", "Evrika"];
const FEATURES = [
  ["01", "Item-by-Item Sourcing", "Every missing ingredient is compared independently. Butter can come from Yerevan City while chicken comes from Carrefour—only when the numbers work."],
  ["02", "7-Day Bulk-Reuse Planner", "Recipes are selected together, rewarding overlapping grains, herbs and proteins so one purchase serves several meals instead of becoming waste."],
  ["03", "Local Market Sourcing", "Armenian store inventories, package sizes and native AMD prices make each basket immediately understandable."],
  ["04", "Zero-Cost Directions", "Every selected store includes a direct Google Maps route intent. No paid Maps SDK, payment gateway or API key is required."],
];
const FAQ = [
  ["Which Armenian stores are covered?", "The demo catalog models Yerevan City, SAS, Carrefour, Parma and Evrika. The sourcing layer can also accept neighborhood-store data and always provides a safe local fallback."],
  ["Can I exclude allergens or disliked ingredients?", "Yes. Exclusions are strict guardrails across search, recipe recommendations and the automatic weekly planner. Favorite dishes influence ranking without overriding safety preferences."],
  ["Does pantry tracking work without live store data?", "Yes. Pantry quantities, expiration dates, recipe coverage and meal deductions are stored in your account. If a live store lookup is unavailable, sourcing uses clearly identified fallback estimates."],
  ["Why might one-store shopping still be recommended?", "The app compares ingredient savings with added travel. You always see the item-by-item schedule, the one-store baseline and the route-adjusted difference before deciding."],
];

export function Welcome({ onLogin, onRegister, currencySwitcher }) {
  const [budget, setBudget] = useState(30000);
  const savings = Math.round(budget * (.09 + (budget - 12000) / 180000));
  const optimized = budget - savings;
  return <main className="min-h-screen overflow-hidden bg-slate-100/70">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-6">
      <BrandMark onClick={() => scrollTo({ top: 0, behavior: "smooth" })}/>
      <div className="flex items-center gap-2">{currencySwitcher}<button onClick={onLogin} className="hidden rounded-xl px-4 py-2 font-bold text-emerald-700 sm:block">Login</button><button onClick={onRegister} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white shadow-lg shadow-emerald-700/10">Get Started Free</button></div>
    </nav>

    <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 pb-24 pt-12 lg:grid-cols-[1.05fr_.95fr]">
      <div className="absolute -left-40 top-12 h-80 w-80 rounded-full bg-slate-800/15 blur-3xl"/>
      <div className="relative animate-rise"><p className="inline-flex rounded-full bg-slate-100 px-4 py-2 text-sm font-extrabold text-slate-800">Built for Armenian kitchens · priced in ֏</p><h1 className="mt-6 text-5xl font-extrabold leading-[.94] tracking-[-.055em] text-zinc-900 sm:text-7xl">Your pantry.<br/><span className="text-emerald-700">Every local price.</span><br/>One smarter week.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-800/70">BariAkhorzhak connects what you own, what your body needs and what nearby stores charge—then builds a practical 7-day diet with less waste and a lower basket.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={onRegister} className="rounded-xl bg-emerald-700 px-6 py-4 font-bold text-white shadow-xl shadow-emerald-700/15">Get Started Free →</button><button onClick={() => document.querySelector("#sample-plan")?.scrollIntoView({ behavior: "smooth" })} className="rounded-xl border border-slate-800/10 bg-white px-6 py-4 font-bold text-zinc-900">Explore Sample Plan</button></div><div className="mt-8 flex flex-wrap gap-2">{CHAINS.map(chain => <span key={chain} className="rounded-full border border-slate-800/10 bg-white/80 px-3 py-2 text-xs font-bold text-slate-800/70">{chain}</span>)}</div></div>

      <div id="sample-plan" className="relative rounded-[2.25rem] bg-zinc-900 p-4 text-white shadow-2xl shadow-zinc-900/20"><div className="rounded-[1.75rem] border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between"><div><small className="font-bold text-slate-100">LIVE APP PREVIEW</small><h2 className="text-xl font-bold">Wednesday plan</h2></div><span className="rounded-full bg-emerald-600 px-3 py-1 text-xs font-bold">84% pantry</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><article className="rounded-2xl bg-white p-4 text-zinc-900"><small className="font-bold text-emerald-700">BREAKFAST</small><b className="mt-2 block">Apricot walnut oats</b><p className="mt-4 text-xs text-slate-800">20g protein · 440 kcal</p></article><article className="rounded-2xl bg-white p-4 text-zinc-900"><small className="font-bold text-emerald-700">DINNER</small><b className="mt-2 block">Chicken khorovats bowl</b><p className="mt-4 text-xs text-slate-800">50g protein · 560 kcal</p></article></div><div className="mt-3 rounded-2xl bg-emerald-700 p-4"><div className="flex justify-between"><span className="font-bold">Granular basket</span><b className="text-amber-500">Save 3,860 ֏</b></div><div className="mt-3 space-y-2 text-sm"><p className="rounded-xl bg-white/10 px-3 py-2">Chicken → Carrefour · 1.4 km</p><p className="rounded-xl bg-white/10 px-3 py-2">Bulgur + herbs → Yerevan City · 0.8 km</p></div></div></div></div>
    </section>

    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-extrabold text-slate-800">ONE SYSTEM, FOUR PRACTICAL ADVANTAGES</p><h2 className="mt-3 max-w-3xl text-4xl font-bold text-zinc-900">From individual shelf prices to a complete, lower-waste week.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{FEATURES.map(([number,title,copy]) => <article key={title} className="rounded-[2rem] border border-slate-800/10 bg-slate-100 p-6 transition hover:-translate-y-1 hover:border-emerald-600/30 hover:shadow-xl"><span className="text-sm font-black text-slate-800">{number}</span><h3 className="mt-3 text-2xl font-bold text-zinc-900">{title}</h3><p className="mt-3 max-w-xl leading-7 text-slate-800/70">{copy}</p></article>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-20 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-extrabold text-slate-800">INTERACTIVE SAVINGS PREVIEW</p><h2 className="mt-3 text-4xl font-bold text-zinc-900">See what item-level shopping can unlock.</h2><p className="mt-4 leading-7 text-slate-800/70">Move the weekly budget. The preview estimates savings from comparing individual ingredients across five Armenian chains.</p></div><div className="rounded-[2rem] bg-zinc-900 p-6 text-white shadow-xl"><div className="flex items-end justify-between gap-4"><div><small className="text-white/50">Weekly grocery budget</small><b className="block text-4xl">{budget.toLocaleString()} ֏</b></div><div className="text-right"><small className="text-amber-500">ESTIMATED SAVINGS</small><b className="block text-3xl text-amber-500">{savings.toLocaleString()} ֏</b></div></div><input aria-label="Weekly grocery budget" type="range" min="12000" max="80000" step="1000" value={budget} onChange={event => setBudget(+event.target.value)} className="mt-7 w-full accent-emerald-600"/><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><small className="text-white/50">One-store estimate</small><b className="block text-xl">{budget.toLocaleString()} ֏</b></div><div className="rounded-2xl bg-emerald-700 p-4"><small className="text-slate-100">Item-by-item estimate</small><b className="block text-xl">{optimized.toLocaleString()} ֏</b></div></div><p className="mt-4 text-xs text-white/45">Illustrative logged-out preview. Signed-in estimates use pantry shortages, package sizes, stock and your saved location.</p></div></section>

    <section className="bg-emerald-700 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2"><div><p className="text-sm font-extrabold text-slate-100">ARMENIAN FOOD, MODERN PLANNING</p><h2 className="mt-3 text-4xl font-bold">Seasonal Ararat Valley produce meets measurable nutrition.</h2></div><p className="text-lg leading-8 text-slate-100/75">Build around apricots, tomatoes, herbs, legumes, matzoon and familiar dishes such as Spas, Ghapama, Harissa and Ishkhan. Your favorites shape ranking while allergen and dislike exclusions remain strict.</p></div></section>

    <section className="mx-auto max-w-5xl px-6 py-20"><div className="text-center"><p className="text-sm font-extrabold text-slate-800">COMMUNITY QUESTIONS</p><h2 className="mt-3 text-4xl font-bold text-zinc-900">Clear answers before you begin.</h2></div><div className="mt-10 space-y-3">{FAQ.map(([question,answer]) => <details key={question} className="group rounded-2xl border border-slate-800/10 bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between font-bold text-zinc-900">{question}<span className="text-xl text-emerald-700 group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl leading-7 text-slate-800/70">{answer}</p></details>)}</div><div className="mt-12 rounded-[2rem] bg-slate-100 p-7 text-center"><h3 className="text-2xl font-bold text-zinc-900">Join a smarter Armenian kitchen community.</h3><p className="mt-2 text-slate-800/70">Track pantry stock, share fresher local price signals and make every dram work harder.</p><button onClick={onRegister} className="mt-5 rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Create your free plan</button></div></section>
  </main>;
}
